alogentpractices/Pages/AccountStatusList.cshtml.cs
using alogentpractices.DAL;
using alogentpractices.Entities;
using alogentpractices.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace alogentpractices.Pages
{
    public class AccountStatusListModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly AccountStatusListService _accountStatusListService;

        public AccountStatusListModel(ApplicationDbContext context, AccountStatusListService accountStatusListService)
        {
            _context = context;
            _accountStatusListService = accountStatusListService;
        }

        public IList<AccountClass> AccountClass { get;set; } = default!;
        public string LoanAccountStatusList = string.Empty;
        public string AccountClassId = string.Empty;

        public async Task OnGetAsync()
        {
            AccountClassId = Request.Query["accountClassId"];
            var loanAccountStatusList = await _accountStatusListService.LoadAccountStatus(int.Parse(AccountClassId));
            LoanAccountStatusList = JsonConvert.SerializeObject(loanAccountStatusList);

            AccountClass = await _context.AccountClasses
                .Include(a => a.LoanStatuses)
                .OrderBy(x => x.accountClassSortOrder)
                .ToListAsync();
        }
    }
}

alogentpractices/Pages/AccountStatusMain.cshtml.cs
using alogentpractices.DAL;
using alogentpractices.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace alogentpractices.Pages
{
    public class AccountStatusMainModel : PageModel
    {
        public string PageTitle = "Account status main";
        
        [BindProperty]
        public LoanStatus loanStatus { set; get; }

        private readonly ApplicationDbContext _context;

        public AccountStatusMainModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public void OnGet()
        {
            loanStatus = new LoanStatus
            {
                statusId = 2,
                statusDescription = "",
                statusCode = "",
                isDefault = true,
                isActive = true,
                accountClassId = 1,
                isApplicationStatus = false,
                accountCount = 0
            };
        }

        public IActionResult OnPostSave()
        {
            if (loanStatus == null)
            {
                return Page();
            }

            var lastRecord = _context.LoanStatuses.OrderByDescending(x => x.statusId).First();
            loanStatus.statusId = lastRecord.statusId + 1;

            _context.LoanStatuses.Add(loanStatus);
            _context.SaveChanges();

            return RedirectToPage("/accountstatuslist", new { accountClassId = 1 });
        }
    }
}

alogentpractices/Pages/Employees.cshtml.cs
using alogentpractices.DAL;
using alogentpractices.Entities;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace alogentpractices.Pages
{
    public class EmployeesModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EmployeesModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Employee> Employee { get;set; } = default!;

        public async Task OnGetAsync()
        {
            Employee = await _context.Employees.ToListAsync();
        }
    }
}

alogentpractices/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace alogentpractices.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

alogentpractices/Pages/ExpiredQ2.cshtml.cs
using alogentpractices.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;

namespace alogentpractices.Pages
{
    public class ExpiredQ2Model : PageModel
    {
        [BindProperty]
        public string searchName{ get; set; }
        [BindProperty]
        public string searchCustomerNumber { get; set; }
        [BindProperty]
        public string searchTaxId { get; set; }
        [BindProperty]
        public string searchCustomerStatus { get; set; }
        [BindProperty]
        public string searchLoan { get; set; }
        [BindProperty]
        public string searchLoanStatus { get; set; }
        [BindProperty]
        public string searchLoanTypeId { get; set; }
        [BindProperty]
        public string searchLoanOfficer { get; set; }
        [BindProperty]
        public string searchBank { get; set; }
        [BindProperty]
        public string searchCustomerTypeId { get; set; }
        [BindProperty]
        public string searchFromLoanOrgDate { get; set; }
        [BindProperty]
        public string searchToLoanOrgDate { get; set; }
        [BindProperty]
        public string searchPageSize { get; set; }
        [BindProperty]
        public string searchCustomerOfficer { get; set; }
        [BindProperty]
        public string searchLoanDescription { get; set; }
        [BindProperty]
        public string searchCustomerBranch { get; set; }
        [BindProperty]
        public string searchLoanBranch { get; set; }
        [BindProperty]
        public string searchClassificationId { get; set; }
        [BindProperty]
        public string searchAccountClassId { get; set; }
        [BindProperty]
        public string searchMaxResult { get; set; }
        [BindProperty]
        public string searchDocumentFilter { get; set; }
        [BindProperty]
        public string searchDisplayDocs { get; set; }
        [BindProperty]
        public string searchAppDateFrom { get; set; }
        [BindProperty]
        public string searchAppDateTo { get; set; }
        [BindProperty]
        public string searchAppLender { get; set; }
        [BindProperty]
        public string searchAppDelegate { get; set; }
        [BindProperty]
        public string searchAppAnalyst { get; set; }
        [BindProperty]
        public string searchApprovalStatusId { get; set; }
        [BindProperty]
        public string searchLoanStatusId { get; set; }
        [BindProperty]
        public string searchAppApprover { get; set; }
        public void OnGet()
        {
        }

        //GetAccountClassByLoanType

        //GetAllAccountClasses
        public List<AccountClass> getAllAccountClasses()
        {
                //using (var conn = new SqlConnection("YourConnectionString"))  //ADO.Net Connection String
                //using (var cmd = new SqlCommand("SELECT accountClassName, accountClassCode, accountClassId FROM AccountClasses", conn))
                //{
                //    conn.Open();
                //    using (var reader = cmd.ExecuteReader())
                //    {
                //        while (reader.Read())
                //        {
                //            accountClasses.Add(new
                //            {
                //                AccountClassName = reader["accountClassName"].ToString(),
                //                AccountClassCode = reader["accountClassCode"].ToString(),
                //                AccountClassId = Convert.ToInt32(reader["accountClassId"])
                //            });
                //        }
                //    }
                //}

            List<AccountClass> accClassesList = new List<AccountClass>
            {
                new AccountClass{accountClassId =101,accountClassCode="001",accountClassName="Test Acc class 1"},
                new AccountClass{accountClassId =102,accountClassCode="002",accountClassName="Test Acc class 2"},
                new AccountClass{accountClassId =103,accountClassCode="003",accountClassName="Test Acc class 3"},
                new AccountClass{accountClassId =104,accountClassCode="004",accountClassName="Test Acc class 4"},
            };
            
            return accClassesList;
        }
        public string GetAccountClassByLoanType(string loanTypeId)
        {
            string resultId = "101"; // null; // Mocking
            //string sqlQuery = "";@* "SELECT accountClassId FROM loanType WHERE loanTypeId = @loanTypeId"; *@
                        
            // using (var connection = new SqlConnection(ConnectionString))
            // {
            //     resultId = connection.ExecuteScalar<string>(sqlQuery, new { loanTypeId });
            // }

            return resultId;
        }



        public List<DocumentItem> BuildTabList(
            string tabType,
            int accountClassId,
            string searchCustomerTypeId,
            string searchLoanTypeId,
            string connectionString)
        {
            //    var documents = new List<DocumentItem>();

            //    using (var conn = new SqlConnection(connectionString))
            //    using (var cmd = conn.CreateCommand())
            //    {
            //        string baseQuery = @"
            //        SELECT DISTINCT
            //            dt.documentTypeId,
            //            dt.documentTypeName,
            //            dst.documentSubTypeId,
            //            dst.documentSubTypeName
            //        FROM documentType dt
            //        INNER JOIN documentSubType dst ON dt.documentTypeId = dst.documentTypeId
            //        LEFT OUTER JOIN documentDefinitions dd ON dd.documentTypeId = dt.documentTypeId AND dd.documentSubTypeId = dst.documentSubTypeId
            //    ";

            //        string whereClause = @" WHERE (ISNULL(dd.requireExpDate, 0) = 1 OR dst.subTypeRequireExpDateYN LIKE 'Y')
            //                           AND dt.typeCode LIKE @tabType
            //                           AND dst.documentSubTypeId IN (SELECT documentSubTypeId FROM documentDefinitions)";

            //        string joinClause = "";
            //        string filterClause = "";

            //        if (tabType == "C")
            //        {
            //            // Customer logic with optional customerType filter
            //            if (!string.IsNullOrEmpty(searchCustomerTypeId))
            //            {
            //                filterClause = " AND dd.customerTypeId = @searchCustomerTypeId";
            //                cmd.Parameters.AddWithValue("@searchCustomerTypeId", searchCustomerTypeId);
            //            }
            //        }
            //        else
            //        {
            //            // Loan logic with extra joins and filters
            //            joinClause = @"
            //            INNER JOIN documentTabAccountSecurity dtas ON dtas.documentSubTypeId = dst.documentSubTypeId AND dtas.accountClassId = @accountClassId
            //        ";

            //            if (!string.IsNullOrEmpty(searchLoanTypeId))
            //            {
            //                filterClause = " AND dd.loanTypeId = @searchLoanTypeId";
            //                cmd.Parameters.AddWithValue("@searchLoanTypeId", searchLoanTypeId);
            //            }

            //            cmd.Parameters.AddWithValue("@accountClassId", accountClassId);
            //        }

            //        cmd.CommandText = baseQuery + joinClause + whereClause + filterClause + @"
            //        ORDER BY dt.documentTypeName, dst.documentSubTypeName";

            //        cmd.Parameters.AddWithValue("@tabType", tabType);

            //        conn.Open();

            //        using (var reader = cmd.ExecuteReader())
            //        {
            //            while (reader.Read())
            //            {
            //                documents.Add(new DocumentItem
            //                {
            //                    DocumentTypeId = Convert.ToInt32(reader["documentTypeId"]),
            //                    DocumentTypeName = reader["documentTypeName"].ToString(),
            //                    DocumentSubTypeId = Convert.ToInt32(reader["documentSubTypeId"]),
            //                    DocumentSubTypeName = reader["documentSubTypeName"].ToString()
            //                });
            //            }
            //        }
            //    }
            List<DocumentItem> documents = new List<DocumentItem> { 
            new DocumentItem{DocumentTypeId=101,DocumentTypeName="DocTypeTest1",DocumentSubTypeId=201, DocumentSubTypeName="DocSubTypeTest1"},

            new DocumentItem{DocumentTypeId=102,DocumentTypeName="DocTypeTest2",DocumentSubTypeId=202, DocumentSubTypeName="DocSubTypeTest2"},

            new DocumentItem{DocumentTypeId=103,DocumentTypeName="DocTypeTest3",DocumentSubTypeId=203, DocumentSubTypeName="DocSubTypeTest3"},

            new DocumentItem{DocumentTypeId=104,DocumentTypeName="DocTypeTest4",DocumentSubTypeId=204, DocumentSubTypeName="DocSubTypeTest4"}
        };

            return documents;
        }
    

}
}

alogentpractices/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace alogentpractices.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(IHttpContextAccessor httpContext, ILogger<IndexModel> logger)
        {
            httpContext.HttpContext.Session.SetInt32("accuaccount.enableExpress", 0); // means false
            httpContext.HttpContext.Session.SetString("isSuperUser", "True");
            httpContext.HttpContext.Session.SetString("credit.isAdmin", "True");
            httpContext.HttpContext.Session.SetString("credit.allowAdd", "True");
            httpContext.HttpContext.Session.SetString("UseBranchSecurity", "Y");
            httpContext.HttpContext.Session.SetInt32("BranchAccessCount", 5);
            httpContext.HttpContext.Session.SetString("accuaccount.disableImaging", "0");
            httpContext.HttpContext.Session.SetString("acculoan.showParticipationLoan", "1");
            httpContext.HttpContext.Session.SetInt32("accuaccount.enableNotices", 1);
            httpContext.HttpContext.Session.SetString("AccuAccount.Notice::Manage", "0");
            httpContext.HttpContext.Session.SetString("AccuAccount.Notice::Distribute", "0");
            httpContext.HttpContext.Session.SetString("AccuAccount.Audit::Manage", "0");
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

alogentpractices/Pages/ManageAccountStatus.cshtml.cs
using alogentpractices.DAL;
using alogentpractices.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace alogentpractices.Pages
{
    public class ManageAccountStatusModel : PageModel
    {
        public string PageTitle = "Account status main";

        [BindProperty]
        public TaskGroupType TaskGroupTypes { set; get; }

        private readonly ApplicationDbContext _context;
        public string BankId = string.Empty;

        public ManageAccountStatusModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public void OnGet()
        {
            BankId = Request.Query["bankId"];
            var TaskGroupTypeId = Request.Query["taskGroupType"];
            if (BankId == null || BankId == "0")
            {
                TaskGroupTypes = new TaskGroupType
                {
                    TaskGroupId = 0
                };
            }
            else
            {
                TaskGroupTypes = _context.TaskGroupTypes.FirstOrDefault(x => x.TaskGroupId == int.Parse(TaskGroupTypeId));
            }
        }

        public IActionResult OnPostSave()
        {
            if (TaskGroupTypes == null)
            {
                return Page();
            }

            if (TaskGroupTypes.TaskGroupId == 0)
            {
                var lastRecord = _context.TaskGroupTypes.OrderByDescending(x => x.TaskGroupId).First();
                TaskGroupTypes.TaskGroupId = lastRecord.TaskGroupId + 1;

                //this i filled only for testing 
                string processing = TaskGroupTypes.TaskProcessing; // "C" or "L"
                string label = TaskGroupTypes.TaskGroupLabel;

                _context.TaskGroupTypes.Add(TaskGroupTypes);
            }
            else
            {

                _context.TaskGroupTypes.Update(TaskGroupTypes);
            }

            _context.SaveChanges();

            return RedirectToPage("/TaskGroupList", new { bankid = "1" });
        }
    }
}

alogentpractices/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace alogentpractices.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

alogentpractices/Pages/SearchResults.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace alogentpractices.Pages
{
    public class SearchResultsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

alogentpractices/Pages/AccountStatusMain.cshtml
@page
@using alogentpractices.Pages
@model AccountStatusMainModel
@{
    Layout = null;
    var isApplicationStatus = false;
}

<div>
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/themes/11.0.2/default/default-main.css" />
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2025.2.702/js/kendo.all.min.js"></script>
    <script src="./js/telerik-license.js"></script>

    <form method="post" asp-page-handler="Save" id="frmAccountStatusMaint">
        <input type="hidden" name="Action" value="Add" />
        <input type="hidden" name="AccountClassId" value="@Model.loanStatus.accountClassId" />
        <input type="hidden" name="StatusId" value="@Model.loanStatus.statusId" />
        <input type="hidden" name="IsApplicationStatus" value="@Model.loanStatus.isApplicationStatus" />
        <table class="aa-two-column-form-table">
            <tr>
                <td>Status Name</td>
                <td><input type="text" class="k-textbox" name="StatusDescription" value="@Model.loanStatus.statusDescription" size="40" /></td>
            </tr>
            <tr>
                <td>Status Code</td>
                <td><input type="text" class="k-textbox" name="StatusCode" value="@Model.loanStatus.statusCode" size="20" /></td>
            </tr>
            @if (isApplicationStatus)
            {
                <tr>
                    <td>Active Status?</td>
                    <td>
                        <select id="cboIsActiveApplicationStatus" name="IsActiveApplicationStatus">
                            <option value="0" selected="@(Model.loanStatus.isActiveApplicationStatus ? "" : "selected")">No</option>
                            <option value="1" selected="@(Model.loanStatus.isActiveApplicationStatus ? "selected" : "")">Yes</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>Default Status?</td>
                    <td>
                        <select id="cboIsDefaultApplicationStatus" name="IsDefaultApplicationStatus">
                            <option value="0" selected="@(Model.loanStatus.isDefaultApplicationStatus ? "" : "selected")">No</option>
                            <option value="1" selected="@(Model.loanStatus.isDefaultApplicationStatus ? "selected" : "")">Yes</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>Approved Status?</td>
                    <td>
                        <select id="cboIsApprovedApplicationStatus" name="IsApprovedApplicationStatus">
                            <option value="0" selected="@(Model.loanStatus.isApprovedApplicationStatus ? "" : "selected")">No</option>
                            <option value="1" selected="@(Model.loanStatus.isApprovedApplicationStatus ? "selected" : "")">Yes</option>
                        </select>
                    </td>
                </tr>
            }
            else
            {
                <tr>
                    <td>Active Status?</td>
                    <td>
                        <select id="cboIsActive" name="IsActive">
                            <option value="0" selected="@(Model.loanStatus.isActive ? "" : "selected")">No</option>
                            <option value="1" selected="@(Model.loanStatus.isActive ? "selected" : "")">Yes</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>Default Status?</td>
                    <td>
                        <select id="cboIsDefaultYN" name="IsDefaultYN">
                            <option value="N" selected="@(!Model.loanStatus.isDefault ? "" : "selected")">No</option>
                            <option value="Y" selected="@(Model.loanStatus.isDefault ? "selected" : "")">Yes</option>
                        </select>
                    </td>
                </tr>
            }
        </table>
        <div class="aa-button-wrapper-absolute">
            <div style="margin-top: 20px;">
                <button id="btnUpdate" type="button" class="k-button k-button-solid-success" onclick="validate();" style="margin-right: 10px;">Update</button>
                <button id="btnCancel" type="button" class="k-button" onclick="parent.closeKendoDialog();">Cancel</button>
            </div>
        </div>
    </form>
    <script>
        $(document).ready(function () {
            // Initialize Kendo Buttons
            $("#btnUpdate").kendoButton({
                click: function () {
                    validate();
                }
            });

            $("#btnCancel").kendoButton({
                click: function () {
                    parent.closeKendoDialog();
                }
            });
        });

        $(document).ready(function () {
            $("select").each(function () {
                $(this).kendoDropDownList();
            });
        });

        function validate() {
            var form = document.getElementById('frmAccountStatusMaint');
            if (!form.StatusDescription.value) {
                alert('Please enter the status name');
                form.StatusDescription.focus();
                return;
            }
            if (!form.StatusCode.value) {
                alert('Please enter the status code');
                form.StatusCode.focus();
                return;
            }
            form.submit();
        }
    </script>
</div>

alogentpractices/Pages/ManageAccountStatus.cshtml
@page
@using alogentpractices.Pages
@model alogentpractices.Pages.ManageAccountStatusModel
@{
    ViewData["Title"] = "Add Edit TaskGroupType";
}

<style>
    table.aa-two-column-form-table div {
        font-size: 16px !important;
        font-weight: 600;
    }

    .gap {
        margin-left: 1rem !important;
    }

    .group-name {
        border: 1px solid #d9d9d9;
        border-radius: 3px;
        padding: 3px 8px;
    }
</style>

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
<script src="~/Packages/jquery/jquery.min.js"></script>
<script src="~/Packages/kendo-ui/js/kendo.all.min.js"></script>
<link href="./css/styles.css" rel="stylesheet" />

<div class="aa-title" style="background: rgb(245 245 245); border: 1px solid #d9d9d9;">
    <div class="d-flex justify-content-between" style="margin-left: 9rem; height: 40px; align-items: center;">
        <div style="font-weight: 600; color: #545454;">
            <i class="title-icon fas fa-file-alt"></i>
            Task Group Maintenance: Add New Credit Task Group
            <a asp-page="/AdminList" class="ps-1 aa-command-button arrow-icon">
                <i class="aa-icon fas fa-arrow-circle-left fa-fw" title="Return to Admin Area"></i>
            </a>
        </div>
        <div id="aa-bank-logo-container">
            <img src="/customer/logo/customerlogo.gif" alt="logo" id="customer-logo-image" />
        </div>
    </div>
</div>

<div id="aa-task-groups" style="height: 100vh;" class="">
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/themes/11.0.2/default/default-main.css" />
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2025.2.702/js/kendo.all.min.js"></script>
    <script src="./js/telerik-license.js"></script>

    <form method="post" asp-page-handler="Save" id="frmAccountStatusMaint" class="p-3" style="padding-bottom: 1rem;
    border-bottom: 1px solid #d9d9d9;">
        <input type="hidden" name="Action" value="Add" />
        <input type="hidden" asp-for="TaskGroupTypes.TaskGroupId" value="@Model.TaskGroupTypes.TaskGroupId" />
        <input type="hidden" asp-for="TaskGroupTypes.ExceptionCount" value="@Model.TaskGroupTypes.ExceptionCount" />
        <input type="hidden" asp-for="TaskGroupTypes.TaskCount" value="@Model.TaskGroupTypes.TaskCount" />

        <table class="aa-two-column-form-table">
            <tr>
                <td>
                    <div style="background: #eae7e7;padding: 5px 18px;width: 250px;">
                        Task Group Name:
                    </div>
                </td>
                <td>
                    <div class="gap">
                        <input type="text" class="k-textbox group-name" asp-for="TaskGroupTypes.TaskGroupLabel" size="40" />
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div style="background: #eae7e7;padding: 5px 18px;width: 250px;">
                        Task Processing:
                    </div>
                </td>
                <td>
                    <div class="gap">
                        <select id="cboTaskProcessing" asp-for="TaskGroupTypes.TaskProcessing">
                            <option value="C" data-label="Credit" selected="@(Model.TaskGroupTypes.TaskProcessing == "C" ? "selected" : "")">Credit</option>
                            <option value="L" data-label="Loan" selected="@(Model.TaskGroupTypes.TaskProcessing == "L" ? "selected" : "")">Loan</option>
                        </select>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div style="background: #eae7e7;padding: 5px 18px;width: 250px;">
                        Task Group Type:
                    </div>
                </td>
                <td>
                    <div class="gap">
                        @if (Model.TaskGroupTypes.TaskProcessing == "C")
                        {
                            <span>Credit</span>
                        }
                        else
                        {
                            <span>Loan</span>
                        }
                    </div>
                </td>
            </tr>
        </table>
        <div class="aa-button-wrapper-absolute">
            <div style="margin-top: 20px;">
                @*  <button id="btnUpdate" type="button" class="button-style button-color text-white k-button" onclick="validate();" style="margin-right: 10px;">Update</button> *@
                <button id="btnUpdate"
                        type="submit"
                        class="button-style button-color text-white k-button"
                        style="margin-right: 10px;">
                    @(Request.Query["bankId"] == "0" ? "Add" : "Update")
                </button>
                <button id="btnCancel" type="button" class="button-style k-button bg-white" style="color: #62a3be !important" onclick="parent.closeKendoDialog();">Cancel</button>
            </div>
        </div>
    </form>
    <script>
        $(document).ready(function () {
            // Initialize Kendo Buttons
            $("#btnUpdate").kendoButton({
                click: function () {
                    validate();
                }
            });

            $("#btnCancel").kendoButton({
                click: function () {
                    parent.closeKendoDialog();
                }
            });
        });

        $(document).ready(function () {
            $("select").each(function () {
                $(this).kendoDropDownList();
            });
        });

        function validate() {
            var form = document.getElementById('frmAccountStatusMaint');
            if (!form.TaskGroupName.value) {
                alert('Please enter the status name');
                form.TaskGroupName.focus();
                return;
            }

            form.submit();
        }
        function updateTaskGroupValues() {
            var select = document.getElementById("cboTaskProcessing");
            var selectedOption = select.options[select.selectedIndex];
            var processingValue = selectedOption.value;
            var labelValue = selectedOption.getAttribute("data-label");

            document.getElementById("TaskGroupProcessing").value = processingValue;
            document.getElementById("TaskGroupLabel").value = labelValue;
        }

        // Optional: Trigger update on page load in case selected option is not default
        document.addEventListener("DOMContentLoaded", function () {
            //updateTaskGroupValues();
        });
    </script>
</div>